# Generated by Django 2.2.1 on 2019-05-04 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("social", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Snippet",
            fields=[
                (
                    "sharable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="social.Sharable",
                    ),
                ),
                ("text", models.TextField()),
            ],
            bases=("social.sharable",),
        )
    ]
