# Generated by Django 2.2.1 on 2019-05-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='avatar',
            field=models.URLField(blank=True),
        ),
    ]
