# Generated by Django 2.2.1 on 2019-05-07 18:48

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20190506_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='avatar',
            field=models.URLField(blank=True, default=social.models.get_avatar),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='desc',
            field=models.TextField(blank=True, default='Apparently, this user prefers to keep an air of mystery about them.'),
        ),
    ]
