# Generated by Django 2.2.1 on 2019-05-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20190507_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharable',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
